name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on: [push]
jobs:
  build_pytohn_cli:
    runs-on: ubuntu-latest
    
    steps:
    
    # Check-out the repository
    - uses: actions/checkout@v3

    - uses: https://github.com/actions/setup-python@v4 
      with:
        python-version: 'pypy3.9'
        # cache: 'pip' # caching pip dependencies

    - run: pip install -r requirements.txt
    
    # Compile to file
    - run: pyinstaller --onefile demo/demo_interactive_serial.py